######################################################################
# Automatically generated by qmake (3.0) Wed Sep 23 16:20:24 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = A1
INCLUDEPATH += .

# Input
HEADERS += game.h renderer.h window.h
SOURCES += game.cpp main.cpp renderer.cpp window.cpp
